language: scala
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_fa993ea8dd40_key -iv $encrypted_fa993ea8dd40_iv
  -in private-key.pem.enc -out private-key.pem -d
- git fetch --tags
install:
- gpg --import public-key.pem
- gpg --import private-key.pem
- gpg --list-keys
stages:
- name: test
- name: release
  if: branch = master AND type = push
jobs:
  include:
  - stage: test
    script: sbt +test
  - stage: release
    script: sbt ci-release-sonatype
before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local
cache:
  directories:
  - "$HOME/.sbt/1.0/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"
