language: scala
jdk: oraclejdk8

before_install:
- git fetch --tags
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then echo b; fi
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then \
    echo c; \
    echo d; \
  fi

stages:
- name: test
- name: release
  if: branch = master

jobs:
  include:
    - stage: test
      script: sbt +test
    - stage: release
      script: sbt ci-release-sonatype

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local
cache:
  directories:
  - "$HOME/.sbt/1.0/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"