language: scala
jdk: openjdk8

before_install:
- git fetch --tags
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then
    openssl aes-256-cbc -K $encrypted_d8ab755c5150_key -iv $encrypted_d8ab755c5150_iv -in private-key.pem.enc -out private-key.pem -d;
    gpg --import private-key.pem;
    gpg --list-keys;
  fi

stages:
- name: test
- name: release
  if: branch = master AND type = push

jobs:
  include:
  - stage: test
    script: sbt +test
  - stage: release
    script: sbt ci-release-sonatype

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local
cache:
  directories:
  - "$HOME/.sbt/1.0/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"
