name: PR
on: pull_request
jobs:
  pr:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: olafurpg/setup-scala@v10
      - run: sbt test
